MODEL:
  NAME: "resnet18"
  PRETRAINED: True
OPTIM:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001
  EPOCH: 10
  BATCH_SIZE: 32
  SCHEDULER:
    TYPE: "Step"
    STEP_SIZE: 5
    GAMMA: 0.1
    COSINE_LR_MIN: 0.0000001
    CYCLE_DIV_FACTOR: 25
DATASET:
  NAME: "CIFAR100"
  INPUT_SIZE: (32, 32)
VISDOM: True
PLOT_EVERY: 20
